language: csharp
sudo: required
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: latest
dotnet: 2.1.4
os:
  - linux
  - osx
osx_image: xcode8.2

script:
  - ./build.sh